name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"  ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: hls-telehealth-installer

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Declare versioning variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - uses: actions/checkout@v3
    - name: Docker Login
      run: # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
      with:
        path: ./
  
    # Build Image from the Dockerfile in Repo
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{steps.package-version.outputs.current-version}} --build-arg BRANCH=${{ steps.vars.outputs.branch }} --build-arg SHA=${{ steps.vars.outputs.sha_short }}

    - name: Get current Version
      run:
        echo "${{steps.package-version.outputs.current-version}}"

    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{steps.package-version.outputs.current-version}}
